# Generated by Django 4.2.4 on 2023-11-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbonherofitness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenge_image',
            field=models.ImageField(blank=True, null=True, upload_to='challenge_images/'),
        ),
        migrations.AddField(
            model_name='content',
            name='content_image',
            field=models.ImageField(blank=True, null=True, upload_to='content_images/'),
        ),
        migrations.AddField(
            model_name='reward',
            name='reward_image',
            field=models.ImageField(blank=True, null=True, upload_to='reward_images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
